export enum ROUTES {
	HOME = '/',
	PRODUCTS = '/systems',
	SIGNIN = '/signin',
	SIGNUP = '/signup',
	ABOUT = '/about-us',
	MEMBER = '/member',
	DOCS = '/docs',
	PRICING = '/pricing',
	TEAM = '/team',
	EVENTS = '/events',
	BLOGS = './blogs',
	WEBDESIGN = '/webdesign',
	TOS = '/terms-of-service',
	PRIVACY = '/privacy-policy',
	CONTACT_US = '/contact',
}
