import Head from 'next/head';
import { Hero, Team, Testimonial, Feature, NewsLetter } from '../components';

import { GetServerSidePropsContext, InferGetServerSidePropsType } from 'next';

export default function indexPage({
	pageComponentProps,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
	return (
		<>
			<Head>
				<title>Home | Welcome to AccessAdvancedSystems </title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Hero />
			<Feature />
			<Team />
			<NewsLetter />
			<Testimonial />
		</>
	);
}

export async function getServerSideProps(ctx: GetServerSidePropsContext) {
	return {
		props: {
			pageComponentProps: {},
		},
	};
}
