import {
	Box,
	Button,
	Flex,
	Heading,
	SimpleGrid,
	Stack,
	Text,
	useColorModeValue as mode,
} from '@chakra-ui/react';
import { NextPage } from 'next';
import Head from 'next/head';
import { FaFacebook, FaGoogle } from 'react-icons/fa';
import * as Logos from '../components/auth/Brands';
import { DividerWithText } from '../components/auth/DividerWithText';
import { Logo } from '../components/auth/Logo';
import { App as Signin } from '../components/auth/signin/App';
import { Testimonial } from '../components/auth/Testimonial';
import { ROUTES } from '../constants/routes';

import { GetServerSidePropsContext, InferGetServerSidePropsType } from 'next';

export default function signinPage({
	pageComponentProps,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
	return (
		<>
			<Head>
				<title>Signin To start Purchasing </title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Signin />
		</>
	);
}

export async function getServerSideProps(ctx: GetServerSidePropsContext) {
	return {
		props: {
			pageComponentProps: { data: {} },
		},
	};
}
